---
ar: يبرعلا
bg: Български
ca: Català
cs: Česky
da: Dansk
de: Deutsch
en: English
es: Español
eo: Esperanto
fa: س راف
fr: Français
ko: 한국어
id: Bahasa Indonesia
it: Italiano
he: עברית
lt: Lietuvių
hu: Magyar
ms: Bahasa Melayu
nl: Nederlands
ja: 日本語
'no': Norsk (bokmål)
pl: Polski
pt: Português
ru: Русский
ro: Română
sk: Slovenčina
sl: Slovenščina
sr: Српски / Srpski
fi: Suomi
sv: Svenska
tr: Türkçe
uk: Українська
vi: Tiếng Việt
vo: Volapük
war: Winaray
zh: 中文