require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SetsController do

  def mock_set(stubs={})
    @mock_set ||= mock_model(Set, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all sets as @sets" do
      Set.stub(:all) { [mock_set] }
      get :index
      assigns(:sets).should eq([mock_set])
    end
  end

  describe "GET show" do
    it "assigns the requested set as @set" do
      Set.stub(:find).with("37") { mock_set }
      get :show, :id => "37"
      assigns(:set).should be(mock_set)
    end
  end

  describe "GET new" do
    it "assigns a new set as @set" do
      Set.stub(:new) { mock_set }
      get :new
      assigns(:set).should be(mock_set)
    end
  end

  describe "GET edit" do
    it "assigns the requested set as @set" do
      Set.stub(:find).with("37") { mock_set }
      get :edit, :id => "37"
      assigns(:set).should be(mock_set)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created set as @set" do
        Set.stub(:new).with({'these' => 'params'}) { mock_set(:save => true) }
        post :create, :set => {'these' => 'params'}
        assigns(:set).should be(mock_set)
      end

      it "redirects to the created set" do
        Set.stub(:new) { mock_set(:save => true) }
        post :create, :set => {}
        response.should redirect_to(set_url(mock_set))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved set as @set" do
        Set.stub(:new).with({'these' => 'params'}) { mock_set(:save => false) }
        post :create, :set => {'these' => 'params'}
        assigns(:set).should be(mock_set)
      end

      it "re-renders the 'new' template" do
        Set.stub(:new) { mock_set(:save => false) }
        post :create, :set => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested set" do
        Set.stub(:find).with("37") { mock_set }
        mock_set.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :set => {'these' => 'params'}
      end

      it "assigns the requested set as @set" do
        Set.stub(:find) { mock_set(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:set).should be(mock_set)
      end

      it "redirects to the set" do
        Set.stub(:find) { mock_set(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(set_url(mock_set))
      end
    end

    describe "with invalid params" do
      it "assigns the set as @set" do
        Set.stub(:find) { mock_set(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:set).should be(mock_set)
      end

      it "re-renders the 'edit' template" do
        Set.stub(:find) { mock_set(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested set" do
      Set.stub(:find).with("37") { mock_set }
      mock_set.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the sets list" do
      Set.stub(:find) { mock_set }
      delete :destroy, :id => "1"
      response.should redirect_to(sets_url)
    end
  end

end
